### ISSUE TITLE
Bolje razdvojiti javni i privatni deo aplikacije u readme fajlu

### ISSUE THREAD

**Issue by 4PixelsDev** [stula85/Imunizacija-2021#2]
Potrebno je jasnije, bar jednom redom razmaka, razdvojiti funkcionalnosti javnog i privatnog dela aplikacije kako neko ne bi pomislio da svako moze da vidi podatke bilo kod drugog gradjanina. Prilikom "skeniranja" Readme-ja skroz sam ispustio podatak da app ima 2 dela.

**Comment by stula85** [comment]
Dragi Igore,
Zahvaljujem Vam se na prijedlogu. Mislim da ste u pravu. Slobodno napravite
izmenu na readme fajlu (napravite razmak) pa ću uraditi merge Vaših
promjena.

Pozdrav,
B.

уто, 13. апр 2021. 18:20 Igor Stojanovic ***@***.***> је
написао/ла:
