### ISSUE TITLE
Dodatne akcije na listi imunizacija za pacijenta

### ISSUE THREAD

**Issue by dysk0** [stula85/Imunizacija-2021#7]
- Omogućiti unos vrste vakcine 
- Napomena za vakcinu (revakcinacija, i sl.)
- Unos statusa (pacijent se nije pojavio u terminu)
- Mogućnost pomjeranja termina

**Comment by stula85** [comment]
Tražene mogućnosti su sa posljednjim commit-om dodane u aplikaciju. @dysk0  Molim Vas da provjerite.
